[package]
name = "probes"
version = "0.1.0"
authors = ["Nicolas Fraison <nfraison@yahoo.fr>"]
edition = "2018"

[[bin]]
name = "mempoke"
path = "src/bin/mempoke.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Async scheduler
tokio = { version = "1", features = ["full", "tracing"] }
# Http client
hyper = { version = "0.14", features = ["full"] }
# Other
argparse = "0.2.2"
serde_json = "1.0"
# Log
log = "0.4.0"
env_logger = "0.8.4"
# Debug
console-subscriber = { git = "https://github.com/tokio-rs/console" }