name: Release
on: 
  release:
    types: [published]
jobs:
  build:
    name: Publish artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Rust
        uses: raftario/setup-rust-action@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Directories
        run: mkdir -p output/build-${GITHUB_REF#refs/*/}/bin
      - name: Build
        run: make build
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHR_PATH: target/release/mempoke
