name: Release
on: 
  release:
    types: [published]
jobs:
  build:
    name: Publish artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Rust
        uses: raftario/setup-rust-action@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make build
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHR_PATH: target/release/mempoke
