name: Release with commit

on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: ChanTsune/release-with-commit@v2.4.0
        with:
          regexp: "Release (\\d\\.\\d\\.\\d)"
          release_name: "v$1"
          tag_name: "v$1"
          body: "$1"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'