name: Test
on: [push, pull_request]
jobs:
  test:
    name: Publish artifacts
    runs-on: ubuntu-latest
    steps:
    - name: Rust
      uses: raftario/setup-rust-action@v1
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: make test